[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >=46.4.0",
    "setuptools_scm[toml] >=7",
    "wheel",
]

[tool.ruff]
line-length = 99

[tool.yapf]
based_on_style = "pep8"
column_limit = 99
