# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PTYCHO_CI_DATA_DIR: /local/ptycho_aux_data/ci_data

permissions:
  contents: read

jobs:
  lint:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Create environment
        id: create_env
        run: |
          uv venv --python 3.11 .venv_lint
          source .venv_lint/bin/activate

      - name: Install Ruff
        run: |
          source .venv_lint/bin/activate
          uv pip install ruff==0.11.12

      - name: Run Ruff
        run: |
          source .venv_lint/bin/activate
          ruff check src/ --output-format=github

  linux-x86-gpu:

    defaults:
      run:
        shell: bash -l {0}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Configure Podman GPU access
        run: |
          set -euo pipefail

          GPU_ARGS="--security-opt=label=disable"
          for hook_dir in /usr/share/containers/oci/hooks.d/ /etc/containers/oci/hooks.d/; do
            if [[ -d "${hook_dir}" ]]; then
              GPU_ARGS+=" --hooks-dir=${hook_dir}"
            fi
          done

          if compgen -G "/dev/nvidia*" > /dev/null 2>&1; then
            for dev in /dev/nvidia*; do
              GPU_ARGS+=" --device=${dev}"
            done
          fi

          echo "PODMAN_GPU_ARGS=${GPU_ARGS}" >> "$GITHUB_ENV"

      - name: Update test data
        id: update_test_data
        run: |
          PACKAGE_DIR=$(pwd)
          cd $PTYCHO_CI_DATA_DIR
          git pull origin main
          cd $PACKAGE_DIR

      - name: Run tests in container
        env:
          PTYCHO_CI_DATA_DIR: ${{ env.PTYCHO_CI_DATA_DIR }}
          PODMAN_GPU_ARGS: ${{ env.PODMAN_GPU_ARGS }}
        run: |
          podman run --rm \
            ${PODMAN_GPU_ARGS:-} \
            -v "${PWD}:/workspace" \
            -v "${PTYCHO_CI_DATA_DIR}:${PTYCHO_CI_DATA_DIR}" \
            -e PTYCHO_CI_DATA_DIR="${PTYCHO_CI_DATA_DIR}" \
            -e NVIDIA_VISIBLE_DEVICES=all \
            -e NVIDIA_DRIVER_CAPABILITIES=compute,utility \
            -w /workspace \
            nvcr.io/nvidia/cuda:12.4.1-runtime-ubuntu22.04 \
            bash -lc '
              set -euo pipefail

              export DEBIAN_FRONTEND=noninteractive
              apt-get update
              apt-get install -y --no-install-recommends curl ca-certificates git build-essential

              curl -LsSf https://astral.sh/uv/install.sh | sh
              export PATH="${HOME}/.local/bin:${PATH}"

              uv python install 3.11
              uv sync --locked --python 3.11

              uv run pytest -s --high-tol --save-timing tests

              rm -rf .venv
            '
