# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linux-x86-gpu:

    defaults:
      run:
        shell: bash -l {0}

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Create environment
      run: |
        conda create --quiet --yes --force -n ci_py311 python=3.11
      
    - name: Install dependencies
      run: |
        conda env list
        conda activate ci_py311
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .

    - name: List build environment
      run: conda list -n ci_py311

    - name: Test with pytest
      run: |
        export PTYCHO_CI_DATA_DIR="/local/ptycho_aux_data/ci_data"
        cd tests
        pytest -s --high-tol
